------- load staged files into tables

COPY INTO DATA_ENGINEERING_PORTFOLIO.SFTP_PIPELINE.WORKFORCE_RAW
FROM @DATA_ENGINEERING_PORTFOLIO.SFTP_PIPELINE.STG_WORKFORCE_FILES
FILE_FORMAT = (FORMAT_NAME = DATA_ENGINEERING_PORTFOLIO.SFTP_PIPELINE.FF_WORKFORCE_CSV);
