CREATE OR REPLACE PROCEDURE DATA_ENGINEERING_PORTFOLIO.SFTP_PIPELINE.SP_LOAD_WORKFORCE_WITH_AUDIT()
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE
    v_rows_loaded NUMBER DEFAULT 0;

BEGIN

    COPY INTO DATA_ENGINEERING_PORTFOLIO.SFTP_PIPELINE.WORKFORCE_RAW
    FROM @DATA_ENGINEERING_PORTFOLIO.SFTP_PIPELINE.STG_WORKFORCE_FILES
    FILE_FORMAT = (
        FORMAT_NAME = DATA_ENGINEERING_PORTFOLIO.SFTP_PIPELINE.FF_WORKFORCE_CSV
    );

    SELECT COUNT(*)
    INTO :v_rows_loaded
    FROM DATA_ENGINEERING_PORTFOLIO.SFTP_PIPELINE.WORKFORCE_RAW;

    INSERT INTO DATA_ENGINEERING_PORTFOLIO.SFTP_PIPELINE.LOAD_AUDIT_LOG (
        file_name,
        target_table,
        load_timestamp,
        rows_loaded,
        load_status
    )
    VALUES (
        'workforce_headcount.csv.gz',
        'WORKFORCE_RAW',
        CURRENT_TIMESTAMP(),
        :v_rows_loaded,
        'SUCCESS'
    );

    RETURN 'Load completed successfully';

END;
$$;
