-- Create file format for MES CSV files

CREATE OR REPLACE FILE FORMAT MES_CSV_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
NULL_IF = ('NULL','null','')
TRIM_SPACE = TRUE
EMPTY_FIELD_AS_NULL = TRUE;