USE DATABASE DATA_ENGINEERING_PORTFOLIO;
CREATE SCHEMA IF NOT EXISTS P4_RAW;
CREATE SCHEMA IF NOT EXISTS P4_TRANSFORM;
CREATE SCHEMA IF NOT EXISTS P4_CURATED;
CREATE SCHEMA IF NOT EXISTS P4_DATA_QUALITY;

USE DATABASE DATA_ENGINEERING_PORTFOLIO;
USE SCHEMA P4_RAW;