USE DATABASE DATA_ENGINEERING_PORTFOLIO;
USE SCHEMA P4_RAW;

CREATE OR REPLACE FILE FORMAT P4_RAW.CSV_STANDARD_FORMAT
TYPE = CSV
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1
NULL_IF = ('NULL', 'null', '');