-- =====================================================
-- Project 3: Data Quality Monitoring Framework
-- Create Core Monitoring Tables
-- =====================================================

-- Create schema for the framework
CREATE SCHEMA IF NOT EXISTS PROJECT3_DQ_MONITORING;

-- Table to track each data quality framework run
CREATE OR REPLACE TABLE PROJECT3_DQ_MONITORING.DQ_PIPELINE_RUNS (
    RUN_ID INTEGER AUTOINCREMENT START 1 INCREMENT 1,
    PIPELINE_NAME STRING,
    TARGET_TABLE STRING,
    RUN_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RUN_STATUS STRING,
    TOTAL_CHECKS INTEGER,
    PASSED_CHECKS INTEGER,
    FAILED_CHECKS INTEGER,
    NOTES STRING
);

-- Table storing results of each rule executed
CREATE OR REPLACE TABLE PROJECT3_DQ_MONITORING.DQ_RULE_RESULTS (
    RULE_RESULT_ID INTEGER AUTOINCREMENT START 1 INCREMENT 1,
    RUN_ID INTEGER,
    RULE_NAME STRING,
    TARGET_TABLE STRING,
    RULE_TYPE STRING,
    RULE_STATUS STRING,
    EXPECTED_VALUE STRING,
    ACTUAL_VALUE STRING,
    THRESHOLD_VALUE STRING,
    CHECK_QUERY STRING,
    ERROR_MESSAGE STRING,
    CHECK_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Optional table storing failing records
CREATE OR REPLACE TABLE PROJECT3_DQ_MONITORING.DQ_FAILED_RECORDS (
    FAILED_RECORD_ID INTEGER AUTOINCREMENT START 1 INCREMENT 1,
    RUN_ID INTEGER,
    RULE_NAME STRING,
    TARGET_TABLE STRING,
    RECORD_IDENTIFIER STRING,
    ERROR_DESCRIPTION STRING,
    FAILURE_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);