-- =====================================================
-- Project 3: Data Quality Monitoring Framework
-- Core Data Quality Rules for RAW_WORKFORCE_API_DATA
-- =====================================================

-- Target table:
-- RAW_WORKFORCE_API_DATA

-- 1. Row count check
SELECT COUNT(*) AS ROW_COUNT
FROM RAW_WORKFORCE_API_DATA;

-- 2. Null check on critical fields
SELECT
    SUM(CASE WHEN SERIES_ID IS NULL THEN 1 ELSE 0 END) AS NULL_SERIES_ID_COUNT,
    SUM(CASE WHEN YEAR IS NULL THEN 1 ELSE 0 END) AS NULL_YEAR_COUNT,
    SUM(CASE WHEN PERIOD IS NULL THEN 1 ELSE 0 END) AS NULL_PERIOD_COUNT,
    SUM(CASE WHEN METRIC_VALUE IS NULL THEN 1 ELSE 0 END) AS NULL_METRIC_VALUE_COUNT
FROM RAW_WORKFORCE_API_DATA;

-- 3. Duplicate check on business key
SELECT
    SERIES_ID,
    YEAR,
    PERIOD,
    COUNT(*) AS DUP_COUNT
FROM RAW_WORKFORCE_API_DATA
GROUP BY SERIES_ID, YEAR, PERIOD
HAVING COUNT(*) > 1;

-- 4. Invalid numeric check for METRIC_VALUE
SELECT COUNT(*) AS INVALID_METRIC_VALUE_COUNT
FROM RAW_WORKFORCE_API_DATA
WHERE TRY_TO_NUMBER(METRIC_VALUE) IS NULL
  AND METRIC_VALUE IS NOT NULL;

-- 5. Invalid year format check
SELECT COUNT(*) AS INVALID_YEAR_COUNT
FROM RAW_WORKFORCE_API_DATA
WHERE TRY_TO_NUMBER(YEAR) IS NULL;

-- 6. Freshness check
SELECT MAX(LOAD_TS) AS MAX_LOAD_TS
FROM RAW_WORKFORCE_API_DATA;