-- =====================================================
-- Project 3: Data Quality Monitoring Framework
-- Test Queries
-- =====================================================

-- 1. Preview raw data
SELECT *
FROM RAW_WORKFORCE_API_DATA
LIMIT 20;

-- 2. Total row count
SELECT COUNT(*) AS ROW_COUNT
FROM RAW_WORKFORCE_API_DATA;

-- 3. Check for nulls in critical fields
SELECT
    SUM(CASE WHEN SERIES_ID IS NULL THEN 1 ELSE 0 END) AS NULL_SERIES_ID_COUNT,
    SUM(CASE WHEN YEAR IS NULL THEN 1 ELSE 0 END) AS NULL_YEAR_COUNT,
    SUM(CASE WHEN PERIOD IS NULL THEN 1 ELSE 0 END) AS NULL_PERIOD_COUNT,
    SUM(CASE WHEN METRIC_VALUE IS NULL THEN 1 ELSE 0 END) AS NULL_METRIC_VALUE_COUNT
FROM RAW_WORKFORCE_API_DATA;

-- 4. Check for duplicates
SELECT
    SERIES_ID,
    YEAR,
    PERIOD,
    COUNT(*) AS DUP_COUNT
FROM RAW_WORKFORCE_API_DATA
GROUP BY SERIES_ID, YEAR, PERIOD
HAVING COUNT(*) > 1;

-- 5. Check for non-numeric metric values
SELECT COUNT(*) AS INVALID_METRIC_VALUE_COUNT
FROM RAW_WORKFORCE_API_DATA
WHERE TRY_TO_NUMBER(METRIC_VALUE) IS NULL
  AND METRIC_VALUE IS NOT NULL;

-- 6. Check latest load timestamp
SELECT MAX(LOAD_TS) AS MAX_LOAD_TS
FROM RAW_WORKFORCE_API_DATA;

-- 7. View framework tables
SELECT * FROM PROJECT3_DQ_MONITORING.DQ_PIPELINE_RUNS;
SELECT * FROM PROJECT3_DQ_MONITORING.DQ_RULE_RESULTS;
SELECT * FROM PROJECT3_DQ_MONITORING.DQ_FAILED_RECORDS;

SHOw SCHEMAS;
USE SCHEMA API_WORKFORCE_PIPELINE;