-- Project 2 - API Workforce Data Pipeline
-- Create schema-level objects for the project

CREATE DATABASE IF NOT EXISTS DATA_ENGINEERING_PORTFOLIO;
CREATE SCHEMA IF NOT EXISTS DATA_ENGINEERING_PORTFOLIO.API_WORKFORCE_PIPELINE;

USE DATABASE DATA_ENGINEERING_PORTFOLIO;
USE SCHEMA API_WORKFORCE_PIPELINE;

CREATE OR REPLACE FILE FORMAT FF_WORKFORCE_CSV
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL', 'null', '');

CREATE OR REPLACE STAGE STG_WORKFORCE_API_FILES
    FILE_FORMAT = FF_WORKFORCE_CSV;
