-- Project 2 - API Workforce Data Pipeline
-- Raw table for workforce API data

USE DATABASE DATA_ENGINEERING_PORTFOLIO;
USE SCHEMA API_WORKFORCE_PIPELINE;

CREATE OR REPLACE TABLE RAW_WORKFORCE_API_DATA (
    LOAD_TS TIMESTAMP_NTZ,
    SOURCE_NAME STRING,
    SERIES_ID STRING,
    YEAR STRING,
    PERIOD STRING,
    PERIOD_NAME STRING,
    METRIC_VALUE STRING,
    LATEST_FLAG STRING,
    FOOTNOTES STRING
);
