-- Create file format and stage for API ingestion

USE DATABASE DATA_ENGINEERING_PORTFOLIO;
USE SCHEMA API_WORKFORCE_PIPELINE;

CREATE OR REPLACE FILE FORMAT FF_WORKFORCE_CSV
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL', 'null', '');

CREATE OR REPLACE STAGE STG_WORKFORCE_API_FILES
    FILE_FORMAT = FF_WORKFORCE_CSV;
