-- Load workforce API CSV into raw table

USE DATABASE DATA_ENGINEERING_PORTFOLIO;
USE SCHEMA API_WORKFORCE_PIPELINE;

COPY INTO RAW_WORKFORCE_API_DATA
FROM (
    SELECT
        $1::TIMESTAMP_NTZ,
        $2::STRING,
        $3::STRING,
        $4::STRING,
        $5::STRING,
        $6::STRING,
        $7::STRING,
        $8::STRING,
        $9::STRING
    FROM @STG_WORKFORCE_API_FILES
)
FILE_FORMAT = (FORMAT_NAME = FF_WORKFORCE_CSV);
