-- Create curated workforce trends table

USE DATABASE DATA_ENGINEERING_PORTFOLIO;
USE SCHEMA API_WORKFORCE_PIPELINE;

CREATE OR REPLACE TABLE CURATED_WORKFORCE_TRENDS (
    METRIC_DATE DATE,
    METRIC_NAME STRING,
    SERIES_ID STRING,
    PERIOD_NAME STRING,
    METRIC_VALUE NUMBER(18,2),
    LOAD_TS TIMESTAMP_NTZ
);
