-- Transform raw workforce API data into curated workforce trends table

USE DATABASE DATA_ENGINEERING_PORTFOLIO;
USE SCHEMA API_WORKFORCE_PIPELINE;

INSERT INTO CURATED_WORKFORCE_TRENDS (
    METRIC_DATE,
    METRIC_NAME,
    SERIES_ID,
    PERIOD_NAME,
    METRIC_VALUE,
    LOAD_TS
)
SELECT
    TO_DATE(
        YEAR || '-' ||
        CASE PERIOD
            WHEN 'M01' THEN '01'
            WHEN 'M02' THEN '02'
            WHEN 'M03' THEN '03'
            WHEN 'M04' THEN '04'
            WHEN 'M05' THEN '05'
            WHEN 'M06' THEN '06'
            WHEN 'M07' THEN '07'
            WHEN 'M08' THEN '08'
            WHEN 'M09' THEN '09'
            WHEN 'M10' THEN '10'
            WHEN 'M11' THEN '11'
            WHEN 'M12' THEN '12'
        END || '-01'
    ) AS METRIC_DATE,
    CASE SERIES_ID
        WHEN 'CES3000000001' THEN 'MANUFACTURING_EMPLOYEE_COUNT'
        WHEN 'CES3000000006' THEN 'MANUFACTURING_PRODUCTION_WORKERS'
        WHEN 'CES3000000008' THEN 'MANUFACTURING_AVG_HOURLY_EARNINGS'
        ELSE 'UNKNOWN_METRIC'
    END AS METRIC_NAME,
    SERIES_ID,
    PERIOD_NAME,
    TRY_TO_NUMBER(METRIC_VALUE, 18, 2) AS METRIC_VALUE,
    LOAD_TS
FROM RAW_WORKFORCE_API_DATA
WHERE PERIOD LIKE 'M%'
  AND PERIOD <> 'M13'
  AND TRY_TO_NUMBER(METRIC_VALUE, 18, 2) IS NOT NULL;
