-- Validation queries for workforce API pipeline

USE DATABASE DATA_ENGINEERING_PORTFOLIO;
USE SCHEMA API_WORKFORCE_PIPELINE;

-- Raw row count
SELECT COUNT(*) AS RAW_ROW_COUNT
FROM RAW_WORKFORCE_API_DATA;

-- Curated row count
SELECT COUNT(*) AS CURATED_ROW_COUNT
FROM CURATED_WORKFORCE_TRENDS;

-- Check for null metric dates
SELECT COUNT(*) AS NULL_METRIC_DATE_COUNT
FROM CURATED_WORKFORCE_TRENDS
WHERE METRIC_DATE IS NULL;

-- Check for null metric values
SELECT COUNT(*) AS NULL_METRIC_VALUE_COUNT
FROM CURATED_WORKFORCE_TRENDS
WHERE METRIC_VALUE IS NULL;

-- Check for duplicate business keys
SELECT
    METRIC_DATE,
    SERIES_ID,
    COUNT(*) AS RECORD_COUNT
FROM CURATED_WORKFORCE_TRENDS
GROUP BY
    METRIC_DATE,
    SERIES_ID
HAVING COUNT(*) > 1;

-- Review available metrics
SELECT DISTINCT
    METRIC_NAME,
    SERIES_ID
FROM CURATED_WORKFORCE_TRENDS
ORDER BY SERIES_ID;

-- Review date coverage
SELECT
    MIN(METRIC_DATE) AS MIN_METRIC_DATE,
    MAX(METRIC_DATE) AS MAX_METRIC_DATE
FROM CURATED_WORKFORCE_TRENDS;

-- Sample output
SELECT *
FROM CURATED_WORKFORCE_TRENDS
ORDER BY METRIC_DATE DESC, SERIES_ID
LIMIT 20;
